name: Executar Testes Unitários

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Executar os testes
        run: |
          source venv/bin/activate
          pytest
