name: Telegram Alert NOVO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  send_telegram_alert:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar alerta para o Telegram
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Novo commit no branch main: ${{ github.sha }} \nAutor: ${{ github.actor }} \nMensagem: ${{ github.event.head_commit.message }} \n[Ver commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
